CLASS zcl_lab_12_linux_bama DEFINITION INHERITING FROM zcl_lab_11_system_bama
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_bama IMPLEMENTATION.
ENDCLASS.
