CLASS zcl_lab_19_lion_bama DEFINITION
  PUBLIC
  INHERITING FROM zcl_lab_18_animal_bama
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_19_LION_BAMA IMPLEMENTATION.


  METHOD walk.
    rv_value = |The lion walks|.
  ENDMETHOD.
ENDCLASS.
