CLASS zcl_lab_18_animal_bama DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk RETURNING VALUE(rv_value) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_18_ANIMAL_BAMA IMPLEMENTATION.


  METHOD walk.
    rv_value = |The animal walks|.
  ENDMETHOD.
ENDCLASS.
