CLASS zcl_lab_12_linux_bama DEFINITION INHERITING FROM zcl_lab_11_system_bama
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_12_LINUX_BAMA IMPLEMENTATION.
ENDCLASS.
