CLASS zcl_lab_21_classroom_bama DEFINITION
  PUBLIC
*  FINAL
  CREATE PUBLIC.
*  CREATE PROTECTED.
*  CREATE PRIVATE.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_LAB_21_CLASSROOM_BAMA IMPLEMENTATION.
ENDCLASS.
