CLASS zcl_lab_23_company_bama DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_lab_24_partner_bama.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA capital TYPE string.

ENDCLASS.



CLASS ZCL_LAB_23_COMPANY_BAMA IMPLEMENTATION.
ENDCLASS.
